baseURL: https://rainto.top/
description: "rainto"
languages:
  en:
    languageCode: "zh-CN"

title: 雨巷

outputs:
  home: ["HTML", "RSS", "JSON"]

markup:
  highlight:
    style: rose-pine
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: 首頁
      pageRef: /
      weight: 10
    - name: 归档
      pageRef: /posts
      weight: 20
    - name: 碎语
      pageRef: /memo
      weight: 40
    - name: 搜索
      pageRef: /search
      weight: 50
    - name: 关于
      pageRef: /about
      weight: 60

params:
  author: "Rainto"
  ogimage: /img/avantar.png
  description: "只愿做个闲散的人。"
  social:
    - name: RSS
      link: /index.xml
      rel: bookmark
    - name: B站
      link: https://space.bilibili.com/650313886
    - name: 网易
      link: https://music.163.com/#/artist?id=49898034
    - name: GIT
      link: https://github.com/rainto0322
    - name: EMAIL
      link: mailto:rainto0322@foxmail.com?subject=Hello

taxonomies:
  category: categories
  tag: tags
